---
- hosts: localhost
  connection: local
  vars_files:
    - './vars/main.yml'

  tasks:
    - name: Pull docker image
      docker_image:
        name: "{{ image_name }}"
        rm: true

    - name: Start docker container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: "{{ container_state }}"
        restart: true
        restart_policy: always
        ports:
          - "8080:8080"
        volumes:
          - /scratch/docker/sabnzbd/config:/config
          - /scratch/docker/sabnzbd/downloads:/downloads
          - /scratch/docker/sabnzbd/nzb:/nzb
          - /etc/localtime:/etc/localtime:ro
