---
- hosts: localhost
  connection: local
  vars_files:
    - './vars/main.yml'

  tasks:
    - name: Pull docker image
      docker_image:
        name: "{{ image_name }}"
        rm: true

    - name: Start docker container
      docker_container:
        name: sabnzbd
        image: "{{ image_name }}"
        state: started
        restart: true
        restart_policy: always
        ports:
          - "8080:8080"
        volumes: "{{ item }}"
      with_items: "{{ docker_volumes }}"
